################################################################
#Name: Haproxy 
#Desc: YAML file for creating a k8s cluster with node of 
#      Haproxy. a load-balancer connect to this node (port 5100) 
################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
  labels:
    app: my-haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-haproxy
  template:
    metadata:
      labels:
        app: my-haproxy
    spec:
#      initContainers:
#        - name: init-sysctl
#          image: busybox
#          command:
#            - sysctl
#            - -w
#            - net.ipv4.tcp_congestion_control=bbr
#          securityContext:
#            privileged: true
      containers:
      - name: my-haproxy
        #image: icr.io/k8s-ns/my-haproxy:custom 
        image: my-haproxy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5300
        # securityContext:
        #   allowPrivilegeEscalation: true
        #   readOnlyRootFilesystem: false
        # resources:
        #   requests:
        #     memory: "256Mi"
        #   limits:
        #     memory: "512Mi"
        #      securityContext:
#        sysctls:
#        - name: net.ipv4.tcp_congestion_control
#          value: "bbr"