name: PR check
run-name: "PR #${{ github.event.number }} check (${{ github.sha }})"
on: [pull_request]
jobs:
  static-checks-and-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Setup goimports
        run: go install golang.org/x/tools/cmd/goimports@v0.13.0
      - name: Check go.mod and go.sum
        run: go mod tidy && git diff --exit-code
      - name: Check format
        run: goimports -l -w . && git diff --exit-code
      - name: Run vet check
        run: go vet ./...
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          skip-pkg-cache: true
      - name: Build binaries
        run: make build
  unit-tests:
    needs: static-checks-and-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.20']  
    steps:
    - name: set up go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: setup tparse
      run:  go install github.com/mfridman/tparse@latest
    - name: checkout
      uses: actions/checkout@v3
    - name: run build
      run: make build
    - name: run unit tests
      run: make unit-tests
    