name: PR check
run-name: PR check \#${{ github.event.number }} ({{ github.sha }})
on: [pull_request]
jobs:
  build-and-unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Setup goimports
        run: go install golang.org/x/tools/cmd/goimports@v0.13.0
      - name: Check go.mod and go.sum
        run: go mod tidy && git diff --exit-code
      - name: Check format
        run: goimports -l -w . && git diff --exit-code
      - name: Run vet check
        run: go vet ./...
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
      - name: Build binaries
        run: make build
